### ISSUE TITLE
Correctly size block types and omit comments by default

### ISSUE THREAD

**Issue by WeiN76LQh** [droe/binja-blocks#1]
I think it would be better to correctly size the `Block_literal` struct definitions and just omit the inline comments by default. The comments add unnecessary noise to the decompilation (this is exacerbated by [this issue in BN](https://github.com/Vector35/binaryninja-api/issues/6006)) and the size of the struct definitions is accurately known, just not the field offsets and types. It makes it clearer to the decompiler and user that an assignment to a variable in the block literal is exactly that and not to some unrelated stack variable initialization.

**Comment by droe** [comment]
Closing this issue after having merged #2 and removed the now dead code that adds those comments in particular.

Vector35/binaryninja-api#6006 may still affect other comments added by this plugin though.
