### ISSUE TITLE
`Block_descriptor.layout` is being added in cases where it shouldn't be

### ISSUE THREAD

**Issue by WeiN76LQh** [droe/binja-blocks#3]
I'm seeing `Block_descriptor` definitions with a `layout` field when its clear that the field shouldn't exist. In some cases `layout` was a pointer to a function that was completely unrelated or the field was off the end of a section in the binary.

I'm seeing this in cases where the `Block_literal.flags` field is `0x42000000` and the `Block_descriptor.reserved` field is `0`.

I don't really understand why this is the case. It seems that the omission of the `BLOCK_HAS_EXTENDED_LAYOUT` flag might mean that the `layout` field shouldn't exist but reading some of the `libclosure` code that might not be true. I wonder if its also dependent on the value of the `Block_descriptor.reserved` field? Which I've noticed sometimes has a value thats non-zero.

This is on iOS 18.1.1 I've found instances of these blocks.

**Comment by droe** [comment]
Thank you for the bug report, much appreciated.

So `0x42000000` is `BLOCK_HAS_SIGNATURE|BLOCK_HAS_COPY_DISPOSE`.

I once thought that there are three cases:
a) extended layout, `BLOCK_HAS_SIGNATURE` set, `BLOCK_HAS_EXTENDED_LAYOUT` set
b) "old GC layout", `BLOCK_HAS_SIGNATURE` set, `BLOCK_HAS_EXTENDED_LAYOUT` not set, unsure about `BLOCK_IS_GC` bit but I was hoping it would be set
c) no layout, `BLOCK_HAS_SIGNATURE` not set

However, there also seems to be:
d) ABI.2010.3.16 as per https://clang.llvm.org/docs/Block-ABI-Apple.html that does have a signature field but not a layout field

Would ABI.2010.3.16 line up with what you're seeing?

By "on iOS 18.1.1", you mean you see this with recent system binaries?  If you can point me towards examples, or share samples in private with me, that might help.

Wrong annotations are arguably worse than missing annotations, so I'm thinking it might be better to omit the layout field when the extended layout bit is not set, getting support for ABI.2010.3.16 but removing speculative and very partial support for old GC layout.  I don't know how to interpret the layout field in the GC layout case anyway, and I'm not sure it's relevant without 32bit architecture support.

**Comment by droe** [comment]
@WeiN76LQh could you give #4 a spin and let me know if that looks better?

**Comment by WeiN76LQh** [comment]
> However, there also seems to be: d) ABI.2010.3.16 as per https://clang.llvm.org/docs/Block-ABI-Apple.html that does have a signature field but not a layout field
> 
> Would ABI.2010.3.16 line up with what you're seeing?

I saw this as well and I'm starting to think its missing the `layout` field just because its outdated. The [libclosure source](https://github.com/apple-oss-distributions/libclosure/blob/main/runtime.cpp) isn't really helping either as it doesn't line up with what I'm seeing.

> By "on iOS 18.1.1", you mean you see this with recent system binaries?

Yes, I mean looking at stuff in recent Apple ipsws for iOS. So many of the libraries in DSC utilise blocks so any will do. I've been looking at `Foundation` in an ipsw for iOS 18.1.1 for an iPhone 16 Pro Max.

> @WeiN76LQh could you give #4 a spin and let me know if that looks better?

I think for `__NSConcreteStackBlock` this is an improvement, however I'm noticing with `__NSConcreteGlobalBlock`s with flags set to `0x50000000` that there is a trailing 64-bit value which is almost certainly the `layout` field.

What I think is probably more likely is its something to do with the `reserved` field in the `Block_descriptor`. The value of that field looks very similar to the `flags` field in `Block_literal`. For an `__NSConcreteStackBlock` with `flags` set to `0xc0000000`, I'm seeing `reserved` in its corresponding `Block_descriptor` set to `0xc0008000` and the `layout` field is present. In cases where an `__NSConcreteStackBlock` has `flags` set to `0x42000000`, I'm seeing `reserved` in its corresponding `Block_descriptor` set to `0x0` and no `layout` field. Another example is `0xc6000000` for `flags` and the same value for `reserved` and the `layout` field is present.

Maybe checking the `BLOCK_HAS_SIGNATURE` flag in the `reserved` field in the `Block_descriptor` is the commonality here for determining if the `layout` field is present?

I do think for now though it would probably be better to be more conservative and omit the `layout` field, like the PR does, unless its certain that the field exists. Like you say; "Wrong annotations are arguably worse than missing annotations" and I agree because an additional field thats wrong could overlap an adjacent structure.

**Comment by droe** [comment]
Merged #4 and created new issue #7 for missing layout field.
