### ISSUE TITLE
IndexError: index out of range in Binary Ninja API code

### ISSUE THREAD

**Issue by droe** [droe/binja-blocks#5]
```
[Default] Traceback (most recent call last):
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 361, in _high_level_il_instruction_is_valid
[Default]     return is_valid(view_obj, func_obj[instr])
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/highlevelil.py", line 2477, in __getitem__
[Default]     raise IndexError("index out of range")
[Default] IndexError: index out of range
```

Repro:
- Open target
- Click on function call in HLIL
- Press Escape

Mere presence of a plugin with is_valid handler seems to be enough, it is not needed to execute a plugin command.

Workaround:
- Removing is_valid handler from plugin command registration.

Reported a bug upstream:  Vector35/binaryninja-api#6254

**Comment by WeiN76LQh** [comment]
Yeah I've been experiencing this, seems to be a recently introduced upstream bug

**Comment by droe** [comment]
Disabled `is_valid` in 5b80ee5 to work round this issue.

**Comment by droe** [comment]
Closing this issue here as 0.4.0 does not use `is_valid` anymore, avoiding this upstream bug.
