### ISSUE TITLE
Cannot find `__NSConcreteStackBlock` and `__NSConcreteGlobalBlock` when working with DSC

### ISSUE THREAD

**Issue by WeiN76LQh** [droe/binja-blocks#6]
If you open DSC in Binary Ninja and load the `libsystem_blocks.dylib` library, which contains the `__NSConcreteStackBlock` and `__NSConcreteGlobalBlock` symbols, the plugin won't be able to find them. This is due to the code that finds the symbols limiting them to specific symbol types, i.e.; `binja.SymbolType.ImportedDataSymbol`, `binja.SymbolType.ImportAddressSymbol` and `binja.SymbolType.ExternalSymbol`. I'm not sure the purpose of this but it breaks the plugin when having open DSC in Binary Ninja because the symbols are defined, not imported/external.

**Comment by droe** [comment]
@WeiN76LQh Can you give #13 a go to see if it improves things for you?

Bulk of the code should now work independently of symbol type.

`_define_ns_concrete_block_imports` is still restricted to specific symbol types to prevent creating the wrong data vars.  There is still the problem that in DSC mode, the symbols seem to be unreliably picked up by Binja.  May need to improve `_define_ns_concrete_block_imports` later on in case there are good strategies that don't break things.  But for now, if the symbols are known to Binja, they should be picked up by the plugin regardless of their type.

**Comment by WeiN76LQh** [comment]
> `_define_ns_concrete_block_imports` is still restricted to specific symbol types to prevent creating the wrong data vars. There is still the problem that in DSC mode, the symbols seem to be unreliably picked up by Binja. May need to improve `_define_ns_concrete_block_imports` later on in case there are good strategies that don't break things. But for now, if the symbols are known to Binja, they should be picked up by the plugin regardless of their type.

Are you saying it can be unreliable even if `libsystem_blocks.dylib` is loaded? I think you'll always need that library to be loaded in DSC for the symbols to be present.

I've tested that branch by loading `Foundation` and `libsystem_blocks.dylib` when having DSC open in Binary Ninja and it seems to work fine. It also continues to work fine for standalone Mach-O binaries that import the symbols.

I have found running the plugin in the case mentioned above to run into a number of issues. I'll try to create GitHub issues for each one.

**Comment by droe** [comment]
> Are you saying it can be unreliable even if libsystem_blocks.dylib is loaded? I think you'll always need that library to be loaded in DSC for the symbols to be present.

Yes, but I have to be more precise, it does pick up the symbols, but does not create data vars as I'd expect, and xrefs for them don't seem to work reliably.  Possibly because DSC mode does not work well on my machine.  Looks like severe scalability issues cause it to hog exorbitant amounts of resources.  Loading Foundation grinds Binary Ninja to a halt and causes severe memory pressure.  Loading smaller dylibs works, but analysis is very slow.

> I've tested that branch by loading Foundation and libsystem_blocks.dylib when having DSC open in Binary Ninja and it seems to work fine. It also continues to work fine for standalone Mach-O binaries that import the symbols.
>
> I have found running the plugin in the case mentioned above to run into a number of issues. I'll try to create GitHub issues for each one.

Thanks, appreciate it.

**Comment by WeiN76LQh** [comment]
> Yes, but I have to be more precise, it does pick up the symbols, but does not create data vars as I'd expect, and xrefs for them don't seem to work reliably. Possibly because DSC mode does not work well on my machine. Looks like severe scalability issues cause it to hog exorbitant amounts of resources. Loading Foundation grinds Binary Ninja to a halt and causes severe memory pressure. Loading smaller dylibs works, but analysis is very slow.

Ah, yes they're slowly pushing through a bunch of PRs massively improve DSC processing. If you're not on the latest dev build then I'd recommend that as it may help.

**Comment by droe** [comment]
Merged #13, gonna close this issue and defer further improvements for DSC analysis to separate issue tickets.
