### ISSUE TITLE
Layout field of block descriptors not picked up when `BLOCK_HAS_EXTENDED_LAYOUT` not set

### ISSUE THREAD

**Issue by droe** [droe/binja-blocks#7]
Creating new issue ticket for second issue brought up in #3:

> I'm noticing with __NSConcreteGlobalBlocks with flags set to 0x50000000 that there is a trailing 64-bit value which is almost certainly the layout field.
> 
> What I think is probably more likely is its something to do with the reserved field in the Block_descriptor. The value of that field looks very similar to the flags field in Block_literal. For an __NSConcreteStackBlock with flags set to 0xc0000000, I'm seeing reserved in its corresponding Block_descriptor set to 0xc0008000 and the layout field is present. In cases where an __NSConcreteStackBlock has flags set to 0x42000000, I'm seeing reserved in its corresponding Block_descriptor set to 0x0 and no layout field. Another example is 0xc6000000 for flags and the same value for reserved and the layout field is present.
> 
> Maybe checking the BLOCK_HAS_SIGNATURE flag in the reserved field in the Block_descriptor is the commonality here for determining if the layout field is present?

**Comment by droe** [comment]
I'm seeing this with much older code too, global blocks, reserved is 0, flags are 0x50000000 (`BLOCK_HAS_SIGNATURE|BLOCK_IS_GLOBAL`), and there is a layout u64 of 0 after the signature field that we now don't pick up as a field.  Not convinced it's related to a non-zero reserved field; what we'd need is a good heuristic for deciding when to add a layout field in absence of `BLOCK_HAS_EXTENDED_LAYOUT`.

**Comment by droe** [comment]
Created #18 to track annotation of in-descriptor flags in lieu of the reserved field.

**Comment by droe** [comment]
I suspect at least some of the not picked up layout fields are actually generic block helper fields; flags 0xc0008000 would indicate `BLOCK_GENERIC_HELPER_INLINE`, i.e. a prepended u64 with inline generic helper info.  Created #20 to track picking up generic block helpers properly.

**Comment by droe** [comment]
@WeiN76LQh Could you give #23 a test drive to see if that gives you expected behaviour, especially with blocks that have in-descriptor flags?

(Even with latest dev versions I struggle to get Binja to do meaningful analysis of iOS 18 DSCs w/o running into out-of-memory conditions.)

**Comment by WeiN76LQh** [comment]
Sorry haven't had any time lately, will try and test it out shortly

**Comment by droe** [comment]
No rush, take your time.

**Comment by droe** [comment]
I've been on the lookout for block descriptors with:
- in-descriptor flags
- `BLOCK_GENERIC_HELPER_BIT0` and/or `BLOCK_GENERIC_HELPER_BIT1` set
- `BLOCK_HAS_EXTENDED_LAYOUT` not set

Looking through iOS 18 system binaries, so far I am only finding examples where a layout field of 0 is present after the descriptor.  I have not found any descriptors overlapping with other data structures, or extending across a section boundary.  So I'm thinking that it would be correct to:

- Pick up the layout field even when block generic helper info is present, and
- Annotate the generic helper info when present

That would mean that in-descriptor flags are unrelated to the overlaps.  I'll want to find concrete instances of overlaps in order to figure out what's happening there (ideally outside of the DSC).

**Comment by droe** [comment]
I found instances of blocks with flags `42000000` in iOS 18.2 `/usr/libexec/modelmanagerd`, and indeed, layout fields were omitted there.

I believe the currently best approximation of a solution landed with #23.

If you find any instances of `layout` fields that should not have been picked up, or any instances of `layout` fields that were picked up but should not have been, please do let me know.  I'll leave the current `main` branch there for a few days of testing before I'll do another release.

**Comment by WeiN76LQh** [comment]
From what I've seen I think things are working fine as of version 0.4.0
